def dibujo_victoria_caballo(nombre,numero,fichas):
    print('\n\n\n\n\n\n\n')                                                        
    print('\t\t                     HA GANADO',nombre,'                              ') 
    print('\t\t                                                         |\    /|     ') 
    print('\t\t                                                      ___| \,,/_/     ') 
    print('\t\t                                                   ---__/ \/    \     ') 
    print('\t\t                                                  __--/     (D)  \    ') 
    print('\t\t                                                  _ -/    (_      \   ') 
    print('\t\t                                                 // /       \_ / ==\  ') 
    print('\t\t                           __-------_____--___--/           / \_ O o) ') 
    print('\t\t                          /                                 /   \==/  ') 
    print('\t\t                         /                                 /     ')      
    print('\t\t                        ||          )     ',numero,'           \_/\        ')   
    print('\t\t                        ||         /              _      /  |    ')      
    print('\t\t                        | |      /--______      ___\    /\  :      ')    
    print('\t\t                        | /   __-  - _/   ------    |  |   \ \    ')     
    print('\t\t                         |   -  -   /                | |     \ ) ')      
    print('\t\t                         |  |   -  |                 | )     | |  ')     
    print('\t\t                          | |    | |                 | |    | |  ')      
    print('\t\t                          | |    < |                 | |   |_/   ')     
    print('\t\t                          < |    /__\                <  \   ')          
    print('\t\t                          /__\                       /___\  ')
    print('\t\t                               OBTIENES',fichas,'FICHAS')   
        

